use std::collections::HashMap;
use std::fmt::Write;

use crate::backend::Backend;
use crate::func::Function;
use crate::instr::*;
use crate::module::Module;
use crate::types::*;
use crate::value::{FuncRef, Value};

#[derive(Debug, Default)]
pub struct CBackend {
    names: Vec<String>,
    heap: Vec<bool>,
    counter: u64,
    ctypes: Vec<String>,
    /// Value -> StructType mapping for field name lookup in ExtractValue.
    struct_types: HashMap<u32, StructType>,
}

impl CBackend {
    pub fn new() -> Self {
        Self::default()
    }

    fn ensure(&mut self, v: Value) {
        let idx = v.0 as usize;
        if idx >= self.names.len() {
            self.names.resize(idx + 1, String::new());
            self.heap.resize(idx + 1, false);
            self.ctypes.resize(idx + 1, String::new());
        }
    }

    fn set(&mut self, v: Value, name: String, ctype: String) {
        self.ensure(v);
        self.names[v.0 as usize] = name;
        self.ctypes[v.0 as usize] = ctype;
    }

    fn name(&self, v: Value) -> &str {
        self.names
            .get(v.0 as usize)
            .map(|s| s.as_str())
            .unwrap_or("0")
    }

    fn set_heap(&mut self, v: Value) {
        self.ensure(v);
        self.heap[v.0 as usize] = true;
    }

    fn is_heap(&self, v: Value) -> bool {
        self.heap.get(v.0 as usize).copied().unwrap_or(false)
    }
}

impl Backend for CBackend {
    type Error = String;

    fn compile(&mut self, module: &Module) -> Result<String, Self::Error> {
        let mut out = String::new();

        writeln!(out, "// Generated by Riddle MIR → C backend (C + Boehm GC)").unwrap();
        writeln!(out, "// Compile: gcc -o out out.c -lgc").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "#include <gc.h>").unwrap();
        writeln!(out, "#include <stdint.h>").unwrap();
        writeln!(out, "#include <stdbool.h>").unwrap();
        writeln!(out, "#include <stdio.h>").unwrap();
        writeln!(out, "#include <stdlib.h>").unwrap();
        writeln!(out).unwrap();

        // Emit struct type definitions
        let structs = collect_structs(module);
        for s in &structs {
            writeln!(out, "typedef struct {{").unwrap();
            for (name, ty) in &s.fields {
                writeln!(out, "  {} {};", ctype_of(ty), sanitize(name)).unwrap();
            }
            writeln!(out, "}} {};", s.name).unwrap();
            writeln!(out).unwrap();
        }

        // Forward declarations
        for &fid in &module.function_order {
            let func = &module.functions[fid];
            let ret = ctype_of(&func.ret_type);
            let params: Vec<String> = func.params.iter().map(|p| ctype_of(&p.ty)).collect();
            let sname = sanitize(&func.name);
            writeln!(
                out,
                "{} {}({});",
                ret,
                sname,
                if params.is_empty() {
                    "void".into()
                } else {
                    params.join(", ")
                }
            )
            .unwrap();
        }

        // Extern function declarations
        for ext in &module.externs {
            let params: Vec<String> = ext.params.iter().map(|p| ctype_of(p)).collect();
            writeln!(
                out,
                "extern {} {}({});",
                ctype_of(&ext.ret_type),
                ext.name,
                if params.is_empty() {
                    "void".into()
                } else {
                    params.join(", ")
                }
            )
            .unwrap();
        }
        writeln!(out).unwrap();

        for &fid in &module.function_order {
            let func = &module.functions[fid];
            self.compile_function(func, &mut out)?;
            writeln!(out).unwrap();
        }

        Ok(out)
    }

    fn name(&self) -> &'static str {
        "c"
    }
}

impl CBackend {
    fn compile_function(&mut self, func: &Function, out: &mut String) -> Result<(), String> {
        self.names.clear();
        self.heap.clear();
        self.ctypes.clear();
        self.struct_types.clear();
        self.counter = 0;

        for p in &func.params {
            let ct = ctype_of(&p.ty);
            self.set(p.value, sanitize(&p.name), ct);
        }

        let ret_ct = ctype_of(&func.ret_type);
        let param_strs: Vec<String> = func
            .params
            .iter()
            .map(|p| format!("{} {}", ctype_of(&p.ty), sanitize(&p.name)))
            .collect();

        let sname = sanitize(&func.name);
        write!(out, "{} {} (", ret_ct, sname).unwrap();
        if param_strs.is_empty() {
            write!(out, "void").unwrap();
        } else {
            for (i, p) in param_strs.iter().enumerate() {
                if i > 0 {
                    write!(out, ", ").unwrap();
                }
                write!(out, "{}", p).unwrap();
            }
        }
        writeln!(out, ") {{").unwrap();

        if func.name == "main" {
            writeln!(out, "  GC_INIT();").unwrap();
        }

        for (_bid, block) in func.blocks.iter() {
            if let Some(ref label) = block.label {
                writeln!(out, "block_{}:", label).unwrap();
            }

            for (i, inst) in block.insts.iter().enumerate() {
                let v = Value(block.start_value + i as u32);
                self.emit_inst(inst, v, out)?;
            }

            match &block.terminator {
                Terminator::Return(val) => match val {
                    Some(v) => writeln!(out, "  return {};", self.name(*v)).unwrap(),
                    None => writeln!(out, "  return;").unwrap(),
                },
                Terminator::Branch(target) => {
                    let label = func.blocks[*target].label.as_deref().unwrap_or("?");
                    writeln!(out, "  goto block_{};", label).unwrap();
                }
                Terminator::CondBranch(cond, then_block, else_block) => {
                    let tl = func.blocks[*then_block].label.as_deref().unwrap_or("?");
                    let el = func.blocks[*else_block].label.as_deref().unwrap_or("?");
                    writeln!(out, "  if ({}) goto block_{};", self.name(*cond), tl).unwrap();
                    writeln!(out, "  else goto block_{};", el).unwrap();
                }
            }
        }

        writeln!(out, "}}").unwrap();
        Ok(())
    }

    fn emit_inst(&mut self, inst: &Inst, v: Value, out: &mut String) -> Result<(), String> {
        match &inst.kind {
            InstKind::Const(c) => match c {
                ConstValue::Int(val, _) => {
                    let ct = ctype_of(&inst.ty);
                    let name = fresh_c(&mut self.counter, "i");
                    self.set(v, name.clone(), ct.clone());
                    writeln!(out, "  {} {} = {};", ct, name, val).unwrap();
                }
                ConstValue::Float(val, _) => {
                    let ct = ctype_of(&inst.ty);
                    let name = fresh_c(&mut self.counter, "f");
                    self.set(v, name.clone(), ct.clone());
                    writeln!(out, "  {} {} = {};", ct, name, val).unwrap();
                }
                ConstValue::Bool(val) => {
                    let name = fresh_c(&mut self.counter, "b");
                    self.set(v, name.clone(), "bool".into());
                    writeln!(out, "  bool {} = {};", name, val).unwrap();
                }
                ConstValue::String(val) => {
                    let name = fresh_c(&mut self.counter, "s");
                    self.set(v, name.clone(), "const char*".into());
                    writeln!(out, "  const char* {} = {:?};", name, val).unwrap();
                }
                ConstValue::Char(val) => {
                    let name = fresh_c(&mut self.counter, "ch");
                    self.set(v, name.clone(), "char".into());
                    writeln!(out, "  char {} = {:?};", name, val).unwrap();
                }
                ConstValue::Unit => {
                    // Unit value — declare as an empty struct to avoid undeclared variable use
                    let name = fresh_c(&mut self.counter, "u");
                    self.set(v, name.clone(), "void".into());
                    writeln!(out, "  // unit {}", name).unwrap();
                }
            },

            InstKind::HeapAlloc(_ty) => {
                let ct = ctype_of(&inst.ty);
                let inner_ct = pointee_ct(&inst.ty);
                let name = fresh_c(&mut self.counter, "h");
                self.set(v, name.clone(), ct.clone());
                self.set_heap(v);
                writeln!(
                    out,
                    "  {} {} = ({})GC_MALLOC(sizeof({}));",
                    ct, name, ct, inner_ct
                )
                .unwrap();
            }

            InstKind::Alloca(_ty) => {
                let ct = ctype_of(&inst.ty);
                let inner_ct = pointee_ct(&inst.ty);
                let name = fresh_c(&mut self.counter, "a");
                self.set(v, name.clone(), ct.clone());
                writeln!(out, "  {} {}; // stack", inner_ct, name).unwrap();
            }

            InstKind::Store(value, ptr) => {
                let vn = self.name(*value);
                let pn = self.name(*ptr);
                if self.is_heap(*ptr) {
                    writeln!(out, "  *{} = {};", pn, vn).unwrap();
                } else {
                    writeln!(out, "  {} = {};", pn, vn).unwrap();
                }
            }

            InstKind::Load(ptr) => {
                let name = fresh_c(&mut self.counter, "l");
                let ct = ctype_of(&inst.ty);
                self.set(v, name.clone(), ct.clone());
                if self.is_heap(*ptr) {
                    writeln!(out, "  {} {} = *{};", ct, name, self.name(*ptr)).unwrap();
                } else {
                    writeln!(out, "  {} {} = {};", ct, name, self.name(*ptr)).unwrap();
                }
            }

            InstKind::BinOp(op, lhs, rhs) => {
                let name = fresh_c(&mut self.counter, "b");
                let ct = ctype_of(&inst.ty);
                self.set(v, name.clone(), ct.clone());
                writeln!(
                    out,
                    "  {} {} = {} {} {};",
                    ct,
                    name,
                    self.name(*lhs),
                    binop_c(*op),
                    self.name(*rhs)
                )
                .unwrap();
            }

            InstKind::UnOp(op, operand) => {
                let name = fresh_c(&mut self.counter, "u");
                let ct = ctype_of(&inst.ty);
                self.set(v, name.clone(), ct.clone());
                // Heap pointers are already references — Ref is a no-op
                if matches!(op, UnOp::Ref) && self.is_heap(*operand) {
                    writeln!(out, "  {} {} = {};", ct, name, self.name(*operand)).unwrap();
                } else {
                    let op_str = match op {
                        UnOp::Neg => "-",
                        UnOp::Not => "!",
                        UnOp::Ref => "&",
                        UnOp::MutRef => "&",
                        UnOp::Deref => "*",
                    };
                    writeln!(out, "  {} {} = {}{};", ct, name, op_str, self.name(*operand)).unwrap();
                }
            }

            InstKind::Cmp(op, lhs, rhs) => {
                let name = fresh_c(&mut self.counter, "cmp");
                self.set(v, name.clone(), "bool".into());
                writeln!(
                    out,
                    "  bool {} = {} {} {};",
                    name,
                    self.name(*lhs),
                    cmpop_c(*op),
                    self.name(*rhs)
                )
                .unwrap();
            }

            InstKind::Cast(op, value, target_ty) => {
                let name = fresh_c(&mut self.counter, "cast");
                let ct = ctype_of(target_ty);
                self.set(v, name.clone(), ct.clone());
                let src = self.name(*value);
                // By-value cast: just re-interpret through assignment
                writeln!(out, "  {} {} = ({}){};", ct, name, ct, src).unwrap();
                let _ = op; // cast kind is informational
            }

            InstKind::StructValue(fields) => {
                let name = fresh_c(&mut self.counter, "s");
                let ct = ctype_of(&inst.ty);
                self.set(v, name.clone(), ct.clone());

                // Record struct type for later ExtractValue
                if let Type::Struct(ref st) = inst.ty {
                    self.struct_types.insert(v.0, st.clone());
                }

                let flds: Vec<String> = fields.iter().map(|f| self.name(*f).to_owned()).collect();
                writeln!(out, "  {} {} = {{ {} }};", ct, name, flds.join(", ")).unwrap();
            }

            InstKind::ArrayValue(elements) => {
                let name = fresh_c(&mut self.counter, "arr");
                let ct = ctype_of(&inst.ty);
                self.set(v, name.clone(), ct.clone());
                let els: Vec<String> = elements.iter().map(|e| self.name(*e).to_owned()).collect();
                writeln!(out, "  {} {} = {{ {} }};", ct, name, els.join(", ")).unwrap();
            }

            InstKind::TupleValue(elements) => {
                let name = fresh_c(&mut self.counter, "tup");
                let ct = ctype_of(&inst.ty);
                self.set(v, name.clone(), ct.clone());
                let els: Vec<String> = elements.iter().map(|e| self.name(*e).to_owned()).collect();
                writeln!(out, "  {} {} = {{ {} }};", ct, name, els.join(", ")).unwrap();
            }

            InstKind::ExtractValue(aggregate, index) => {
                let name = fresh_c(&mut self.counter, "ev");
                let ct = ctype_of(&inst.ty);
                self.set(v, name.clone(), ct.clone());

                let base = self.name(*aggregate);
                // Look up field name from struct type
                let field = self
                    .struct_types
                    .get(&aggregate.0)
                    .and_then(|st| st.fields.get(*index))
                    .map(|(fname, _)| sanitize(fname))
                    .unwrap_or_else(|| format!("f{}", index));

                writeln!(out, "  {} {} = {}.{};", ct, name, base, field).unwrap();
            }

            InstKind::FieldPtr(base, index) => {
                let name = fresh_c(&mut self.counter, "fp");
                let ct = ctype_of(&inst.ty);
                self.set(v, name.clone(), ct.clone());

                let base_name = self.name(*base);
                let field = self
                    .struct_types
                    .get(&base.0)
                    .and_then(|st| st.fields.get(*index))
                    .map(|(fname, _)| sanitize(fname))
                    .unwrap_or_else(|| format!("f{}", index));

                writeln!(out, "  {} {} = &{}.{};", ct, name, base_name, field).unwrap();
            }

            InstKind::IndexPtr(base, index) => {
                let name = fresh_c(&mut self.counter, "ip");
                let ct = ctype_of(&inst.ty);
                self.set(v, name.clone(), ct.clone());
                writeln!(
                    out,
                    "  {} {} = &{}[{}];",
                    ct,
                    name,
                    self.name(*base),
                    self.name(*index)
                )
                .unwrap();
            }

            InstKind::Phi(pairs) => {
                let name = fresh_c(&mut self.counter, "phi");
                let ct = ctype_of(&inst.ty);
                self.set(v, name.clone(), ct.clone());
                // ponytail: scalar phi — declared at merge point.
                // Predecessor blocks must write to this variable before branching.
                writeln!(out, "  {} {}; // phi", ct, name).unwrap();
                let _ = pairs;
            }

            InstKind::Call(callee, args) => {
                let ct = ctype_of(&inst.ty);
                let callee_name = match callee {
                    FuncRef::Local(n) => n.clone(),
                    FuncRef::Intrinsic(n) => n.clone(),
                    FuncRef::Extern(n) => n.clone(),
                };
                let args_str: Vec<String> = args.iter().map(|a| self.name(*a).to_owned()).collect();
                // void return — emit call as a statement, no assignment
                if matches!(&inst.ty, Type::Unit | Type::Never | Type::Void) {
                    writeln!(
                        out,
                        "  {}({});",
                        callee_name,
                        args_str.join(", ")
                    )
                    .unwrap();
                    self.set(v, "".into(), "void".into());
                } else {
                    let name = fresh_c(&mut self.counter, "call");
                    self.set(v, name.clone(), ct.clone());
                    writeln!(
                        out,
                        "  {} {} = {}({});",
                        ct,
                        name,
                        callee_name,
                        args_str.join(", ")
                    )
                    .unwrap();
                }
            }
        }
        Ok(())
    }
}

/// Collect unique struct types from all instructions across the module.
fn collect_structs(module: &Module) -> Vec<StructType> {
    let mut seen: HashMap<String, StructType> = HashMap::new();
    for &fid in &module.function_order {
        let func = &module.functions[fid];
        for (_bid, block) in func.blocks.iter() {
            for inst in &block.insts {
                let mut ty = &inst.ty;
                loop {
                    match ty {
                        Type::Struct(st) => {
                            seen.entry(st.name.clone()).or_insert_with(|| st.clone());
                            break;
                        }
                        Type::Ptr(inner) | Type::Ref(inner, _) => ty = inner,
                        _ => break,
                    }
                }
            }
        }
    }
    let mut out: Vec<StructType> = seen.into_values().collect();
    out.sort_by(|a, b| a.name.cmp(&b.name));
    out
}

fn fresh_c(ctr: &mut u64, prefix: &str) -> String {
    *ctr += 1;
    format!("{}{}", prefix, ctr)
}

fn ctype_of(ty: &Type) -> String {
    match ty {
        Type::Int(ity) => match ity {
            IntTy::I8 | IntTy::U8 => "int8_t".into(),
            IntTy::I16 | IntTy::U16 => "int16_t".into(),
            IntTy::I32 | IntTy::U32 => "int32_t".into(),
            IntTy::I64 | IntTy::U64 | IntTy::Isize | IntTy::Usize => "int64_t".into(),
            IntTy::I128 | IntTy::U128 => "__int128".into(),
        },
        Type::Float(fty) => match fty {
            // ponytail: F16 uses C23 _Float16; fall back to float on older compilers
            FloatTy::F16 => "_Float16".into(),
            FloatTy::F32 => "float".into(),
            FloatTy::F64 => "double".into(),
            // ponytail: F128 uses __float128 (GCC/Clang); long double may differ by target
            FloatTy::F128 => "__float128".into(),
        },
        Type::Bool => "bool".into(),
        Type::Char => "char".into(),
        Type::Str => "const char*".into(),
        Type::Ptr(inner) => format!("{}*", ctype_of(inner)),
        Type::Ref(inner, _) => format!("{}*", ctype_of(inner)),
        Type::Struct(s) => s.name.clone(),
        Type::Array(inner) => format!("{}*", ctype_of(inner)),
        Type::Tuple(elems) => {
            let fields: Vec<String> = elems.iter().enumerate()
                .map(|(i, t)| format!("{} f{};", ctype_of(t), i))
                .collect();
            format!("struct {{ {} }}", fields.join(" "))
        }
        Type::Enum(e) => format!("enum_{}", e.name),
        Type::FnPtr(_) => "void*".into(),
        Type::Unit | Type::Never | Type::Void => "void".into(),
    }
}

fn pointee_ct(ty: &Type) -> String {
    match ty {
        Type::Ptr(inner) | Type::Ref(inner, _) => ctype_of(inner),
        _ => "void".into(),
    }
}

fn binop_c(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
        BinOp::BitAnd => "&",
        BinOp::BitOr => "|",
        BinOp::BitXor => "^",
        BinOp::Shl => "<<",
        BinOp::Shr => ">>",
    }
}

fn cmpop_c(op: CmpOp) -> &'static str {
    match op {
        CmpOp::Eq => "==",
        CmpOp::Neq => "!=",
        CmpOp::Lt => "<",
        CmpOp::Gt => ">",
        CmpOp::LtEq => "<=",
        CmpOp::GtEq => ">=",
    }
}

fn sanitize(name: &str) -> String {
    name.replace('-', "_")
        .replace(':', "_")
        .replace('<', "_")
        .replace('>', "_")
}
