use std::collections::{HashMap, HashSet};
use std::fmt::Write;
use std::hash::{DefaultHasher, Hash, Hasher};

use crate::backend::Backend;
use crate::func::Function;
use crate::instr::*;
use crate::module::Module;
use crate::types::*;
use crate::value::{FuncRef, Value};

#[derive(Debug, Default)]
pub struct CBackend {
    names: Vec<String>,
    counter: u64,
    ctypes: Vec<String>,
    /// Value -> StructType mapping for field name lookup in ExtractValue.
    struct_types: HashMap<u32, StructType>,
    /// Count of how many times each value is referenced as an operand.
    use_counts: HashMap<u32, u32>,
    /// Expression text for values inlined at use sites (no variable emitted).
    inline_of: HashMap<u32, String>,
    /// Alloca values name their C storage directly, even when that storage holds a pointer.
    direct_storage: HashSet<u32>,
    needs_runtime: bool,
}

impl CBackend {
    pub fn new() -> Self {
        Self::default()
    }

    fn ensure(&mut self, v: Value) {
        let idx = v.0 as usize;
        if idx >= self.names.len() {
            self.names.resize(idx + 1, String::new());
            self.ctypes.resize(idx + 1, String::new());
        }
    }

    fn set(&mut self, v: Value, name: String, ctype: String) {
        self.ensure(v);
        self.names[v.0 as usize] = name;
        self.ctypes[v.0 as usize] = ctype;
    }

    fn name(&self, v: Value) -> &str {
        if let Some(expr) = self.inline_of.get(&v.0) {
            if expr.is_empty() {
                return "0";
            }
            return expr.as_str();
        }
        self.names
            .get(v.0 as usize)
            .map(|s| s.as_str())
            .filter(|s| !s.is_empty())
            .unwrap_or("0")
    }

    fn set_inline(&mut self, v: Value, expr: String, ctype: String) {
        self.ensure(v);
        self.inline_of.insert(v.0, expr);
        self.ctypes[v.0 as usize] = ctype;
    }

    fn is_indirect(&self, v: Value) -> bool {
        if self.direct_storage.contains(&v.0) {
            return false;
        }
        self.ctypes
            .get(v.0 as usize)
            .map(|ct| ct.ends_with('*'))
            .unwrap_or(false)
    }

    fn record_struct_type(&mut self, v: Value, ty: &Type) {
        if let Some(st) = struct_type_for_field_base(ty) {
            self.struct_types.insert(v.0, st.clone());
        }
    }
}

impl Backend for CBackend {
    type Error = String;

    fn compile(&mut self, module: &Module) -> Result<String, Self::Error> {
        let mut out = String::new();
        self.needs_runtime = module_has_heap_alloc(module) || has_extern(module, "vector_grow");

        writeln!(out, "// Generated by Riddle").unwrap();
        if self.needs_runtime {
            writeln!(out, "// Compile: cc out.c runtime.c -o out").unwrap();
        } else {
            writeln!(out, "// Compile: cc out.c -o out").unwrap();
        }
        writeln!(out).unwrap();
        writeln!(out, "#include <stddef.h>").unwrap();
        writeln!(out, "#include <stdint.h>").unwrap();
        writeln!(out, "#include <stdbool.h>").unwrap();
        writeln!(out, "#include <stdio.h>").unwrap();
        writeln!(out, "#include <stdlib.h>").unwrap();
        writeln!(out, "#include <string.h>").unwrap();
        writeln!(out, "#if defined(__FLT128_MANT_DIG__)").unwrap();
        writeln!(out, "typedef _Float128 riddle_f128;").unwrap();
        writeln!(out, "#elif defined(__SIZEOF_FLOAT128__)").unwrap();
        writeln!(out, "typedef __float128 riddle_f128;").unwrap();
        writeln!(out, "#else").unwrap();
        writeln!(out, "typedef long double riddle_f128;").unwrap();
        writeln!(out, "#endif").unwrap();
        writeln!(out).unwrap();
        if self.needs_runtime {
            writeln!(out, "void rgc_init(void *stack_bottom);").unwrap();
            writeln!(out, "void *rgc_alloc(size_t size);").unwrap();
            writeln!(out, "void rgc_collect(void);").unwrap();
            writeln!(out).unwrap();
        }

        let structs = collect_structs(module);
        for strukt in &structs {
            writeln!(out, "typedef struct {} {};", strukt.name, strukt.name).unwrap();
        }
        if !structs.is_empty() {
            writeln!(out).unwrap();
        }

        for signature in collect_fn_ptrs(module) {
            let params = signature
                .params
                .iter()
                .enumerate()
                .map(|(index, ty)| c_param_decl(ty, &format!("p{index}")))
                .collect::<Vec<_>>();
            writeln!(
                out,
                "typedef {} (*{})({});",
                ctype_of(&signature.ret),
                fn_ptr_name(&signature),
                if params.is_empty() {
                    "void".into()
                } else {
                    params.join(", ")
                }
            )
            .unwrap();
        }
        writeln!(out).unwrap();

        for s in &structs {
            writeln!(out, "struct {} {{", s.name).unwrap();
            for (name, ty) in &s.fields {
                let (pre, suf) = c_decl_parts(ty);
                writeln!(out, "  {} {}{};", pre, sanitize(name), suf).unwrap();
            }
            writeln!(out, "}};").unwrap();
            writeln!(out).unwrap();
        }

        // Built-in fat pointer type for `str` / `&str`
        writeln!(
            out,
            "typedef struct {{ const char* ptr; size_t len; }} riddle_str;"
        )
        .unwrap();
        if has_extern(module, "str_len") {
            writeln!(
                out,
                "static inline size_t str_len(riddle_str s) {{ return s.len; }}"
            )
            .unwrap();
        }
        if has_extern(module, "str_byte") {
            writeln!(
                out,
                "static inline uint8_t str_byte(riddle_str s, size_t i) {{ return (uint8_t)s.ptr[i]; }}"
            )
            .unwrap();
        }
        if has_extern(module, "str_from_raw") {
            writeln!(
                out,
                "static inline riddle_str str_from_raw(int8_t* data, int64_t len) {{ if (len < 0) abort(); return (riddle_str){{ data ? (const char*)data : \"\", (size_t)len }}; }}"
            )
            .unwrap();
        }
        if has_extern(module, "vector_grow") {
            writeln!(
                out,
                "static inline int8_t* vector_grow(int8_t* data, int64_t len, int64_t capacity, int64_t item_size) {{"
            )
            .unwrap();
            writeln!(
                out,
                "  if (len < 0 || capacity < 0 || len > capacity || item_size <= 0 || capacity > INT64_MAX / 2) abort();"
            )
            .unwrap();
            writeln!(
                out,
                "  int64_t next_capacity = capacity == 0 ? 4 : capacity * 2;"
            )
            .unwrap();
            writeln!(
                out,
                "  if ((uint64_t)next_capacity > SIZE_MAX / (uint64_t)item_size) abort();"
            )
            .unwrap();
            writeln!(
                out,
                "  int8_t* next = (int8_t*)rgc_alloc((size_t)next_capacity * (size_t)item_size);"
            )
            .unwrap();
            writeln!(
                out,
                "  if (data && len) memcpy(next, data, (size_t)len * (size_t)item_size);"
            )
            .unwrap();
            writeln!(out, "  return next;").unwrap();
            writeln!(out, "}}").unwrap();
        }
        for external in module
            .externs
            .iter()
            .filter(|external| external.name.starts_with("size_of_ptr__"))
        {
            let Some(parameter) = external.params.first() else {
                continue;
            };
            writeln!(
                out,
                "static inline int64_t {}({}) {{ return (int64_t)sizeof(*value); }}",
                external.name,
                c_param_decl(parameter, "value")
            )
            .unwrap();
        }
        writeln!(out).unwrap();

        // Forward declarations
        for &fid in &module.function_order {
            let func = &module.functions[fid];
            let ret = c_return_type(func);
            let params: Vec<String> = func
                .params
                .iter()
                .enumerate()
                .map(|(index, p)| c_param_decl(&p.ty, &format!("p{index}")))
                .collect();
            let sname = sanitize(&func.name);
            writeln!(
                out,
                "{} {}({});",
                ret,
                sname,
                if params.is_empty() {
                    "void".into()
                } else {
                    params.join(", ")
                }
            )
            .unwrap();
        }

        // Extern function declarations
        for ext in &module.externs {
            if ext.params.iter().any(|ty| matches!(ty, Type::Str)) {
                return Err(format!(
                    "C extern function `{}` cannot take unsized `str`; use `&str`",
                    ext.name
                ));
            }
            if matches!(ext.ret_type, Type::Str) {
                return Err(format!(
                    "C extern function `{}` cannot return unsized `str`; use `&str`",
                    ext.name
                ));
            }
            if is_builtin_extern(&ext.name) {
                continue;
            }
            let params: Vec<String> = ext.params.iter().map(ctype_of_ffi).collect();
            writeln!(
                out,
                "extern {} {}({});",
                ctype_of_ffi(&ext.ret_type),
                ext.name,
                if params.is_empty() {
                    "void".into()
                } else {
                    params.join(", ")
                }
            )
            .unwrap();
        }
        writeln!(out).unwrap();

        for &fid in &module.function_order {
            let func = &module.functions[fid];
            self.compile_function(func, &mut out)?;
            writeln!(out).unwrap();
        }

        Ok(out)
    }

    fn name(&self) -> &'static str {
        "c"
    }
}

impl CBackend {
    fn compile_function(&mut self, func: &Function, out: &mut String) -> Result<(), String> {
        self.names.clear();
        self.ctypes.clear();
        self.struct_types.clear();
        self.inline_of.clear();
        self.direct_storage.clear();
        self.counter = 0;
        self.use_counts = count_uses(func);

        for p in &func.params {
            let ct = ctype_of(&p.ty);
            self.set(p.value, sanitize(&p.name), ct);
            self.record_struct_type(p.value, &p.ty);
        }

        let ret_ct = c_return_type(func);
        let param_strs: Vec<String> = func
            .params
            .iter()
            .map(|p| c_param_decl(&p.ty, &sanitize(&p.name)))
            .collect();

        let sname = sanitize(&func.name);
        write!(out, "{} {} (", ret_ct, sname).unwrap();
        if param_strs.is_empty() {
            write!(out, "void").unwrap();
        } else {
            for (i, p) in param_strs.iter().enumerate() {
                if i > 0 {
                    write!(out, ", ").unwrap();
                }
                write!(out, "{}", p).unwrap();
            }
        }
        writeln!(out, ") {{").unwrap();

        if self.needs_runtime && func.name == "main" {
            writeln!(out, "  int rgc_stack_anchor = 0;").unwrap();
            writeln!(out, "  rgc_init(&rgc_stack_anchor);").unwrap();
        }
        self.predeclare_phi_vars(func, out);

        for (bid, block) in func.blocks.iter() {
            let bid_raw = bid.into_raw();
            if let Some(ref label) = block.label {
                writeln!(out, "block_{}_{}:;", label, bid_raw).unwrap();
            }

            for (i, inst) in block.insts.iter().enumerate() {
                let v = Value(block.start_value + i as u32);
                self.emit_inst(inst, v, out)?;
            }

            match &block.terminator {
                Terminator::Pending => {
                    return Err(format!("block {bid_raw} has no terminator"));
                }
                Terminator::Return(val) => match val {
                    Some(v) => writeln!(out, "  return {};", self.name(*v)).unwrap(),
                    None if func.name == "main" => writeln!(out, "  return 0;").unwrap(),
                    None => writeln!(out, "  return;").unwrap(),
                },
                Terminator::Branch(target) => {
                    self.emit_phi_assignments(func, *target, bid, out, "  ");
                    let tid = target.into_raw();
                    let label = func.blocks[*target].label.as_deref().unwrap_or("?");
                    writeln!(out, "  goto block_{}_{};", label, tid).unwrap();
                }
                Terminator::CondBranch(cond, then_block, else_block) => {
                    let tl = func.blocks[*then_block].label.as_deref().unwrap_or("?");
                    let tid = then_block.into_raw();
                    let el = func.blocks[*else_block].label.as_deref().unwrap_or("?");
                    let eid = else_block.into_raw();
                    let cond = self.name(*cond);
                    if cond.starts_with('(') && cond.ends_with(')') {
                        writeln!(out, "  if {} {{", cond).unwrap();
                    } else {
                        writeln!(out, "  if ({}) {{", cond).unwrap();
                    }
                    self.emit_phi_assignments(func, *then_block, bid, out, "    ");
                    writeln!(out, "    goto block_{}_{};", tl, tid).unwrap();
                    writeln!(out, "  }} else {{").unwrap();
                    self.emit_phi_assignments(func, *else_block, bid, out, "    ");
                    writeln!(out, "    goto block_{}_{};", el, eid).unwrap();
                    writeln!(out, "  }}").unwrap();
                }
                Terminator::Unreachable => {
                    writeln!(out, "  abort();").unwrap();
                }
            }
        }

        writeln!(out, "}}").unwrap();
        Ok(())
    }

    fn predeclare_phi_vars(&mut self, func: &Function, out: &mut String) {
        for (_bid, block) in func.blocks.iter() {
            for (index, inst) in block.insts.iter().enumerate() {
                let InstKind::Phi(_) = &inst.kind else {
                    continue;
                };
                let ct = ctype_of(&inst.ty);
                if ct == "void" {
                    continue;
                }
                let v = Value(block.start_value + index as u32);
                let name = fresh_c(&mut self.counter, "phi");
                self.set(v, name.clone(), ct.clone());
                self.record_struct_type(v, &inst.ty);
                writeln!(out, "  {} {}; // phi", ct, name).unwrap();
            }
        }
    }

    fn emit_inst(&mut self, inst: &Inst, v: Value, out: &mut String) -> Result<(), String> {
        self.record_struct_type(v, &inst.ty);
        match &inst.kind {
            // ponytail: Const values always inlined — no variable emitted.
            InstKind::Const(c) => {
                let ct = ctype_of(&inst.ty);
                let expr = match c {
                    ConstValue::Int(val, _) => format!("(({}){})", ct, val),
                    ConstValue::Float(val, _) => format!("(({}){})", ct, val),
                    ConstValue::Bool(val) => val.to_string(),
                    ConstValue::String(val) => {
                        let (inner, len) = c_string_parts(val);
                        if is_fat_repr(&inst.ty) {
                            format!("(riddle_str){{ \"{}\", {} }}", inner, len)
                        } else {
                            format!("\"{}\"", inner)
                        }
                    }
                    ConstValue::Char(val) => format!("{:?}", val),
                    ConstValue::Unit => String::new(),
                };
                self.set_inline(v, expr, ct);
            }

            InstKind::HeapAlloc(_ty) => {
                let ct = ctype_of(&inst.ty);
                let inner_ct = pointee_ct(&inst.ty);
                let name = fresh_c(&mut self.counter, "h");
                // HeapAlloc: the C variable is a pointer — is_indirect returns true.
                self.set(v, name.clone(), ct.clone());
                writeln!(
                    out,
                    "  {} {} = ({})rgc_alloc(sizeof({}));",
                    ct, name, ct, inner_ct
                )
                .unwrap();
            }

            InstKind::Alloca(_ty) => {
                let inner = match &inst.ty {
                    Type::Ptr(inner) | Type::Ref(inner, _) => inner.as_ref(),
                    _ => &Type::Void,
                };
                let (decl_pre, decl_suf) = c_decl_parts(inner);
                let name = fresh_c(&mut self.counter, "a");
                let ct = format!("{}{}", decl_pre, decl_suf);
                self.set(v, name.clone(), ct);
                self.direct_storage.insert(v.0);
                writeln!(out, "  {} {}{}; // stack", decl_pre, name, decl_suf).unwrap();
            }

            InstKind::Store(value, ptr) => {
                let vn = self.name(*value).to_owned();
                let pn = self.name(*ptr).to_owned();
                let pt_ct = self
                    .ctypes
                    .get(ptr.0 as usize)
                    .map(|s| s.as_str())
                    .unwrap_or("");
                let value_ct = self
                    .ctypes
                    .get(value.0 as usize)
                    .map(|s| s.as_str())
                    .unwrap_or("");
                if pt_ct.ends_with(']') {
                    // Array storage — C doesn't support array assignment, use memcpy
                    writeln!(out, "  memcpy({}, {}, sizeof({}));", pn, vn, pt_ct).unwrap();
                } else if value_ct.ends_with(']') {
                    let destination = if self.is_indirect(*ptr) {
                        pn
                    } else {
                        format!("&{}", pn)
                    };
                    writeln!(
                        out,
                        "  memcpy({}, {}, sizeof({}));",
                        destination, vn, value_ct
                    )
                    .unwrap();
                } else if self.is_indirect(*ptr) {
                    // ponytail: cancel *& when ptr is an inlined &-expression
                    if let Some(inner) = strip_addr_of(&pn) {
                        writeln!(out, "  {} = {};", inner, vn).unwrap();
                    } else {
                        writeln!(out, "  *{} = {};", pn, vn).unwrap();
                    }
                } else {
                    writeln!(out, "  {} = {};", pn, vn).unwrap();
                }
            }

            InstKind::Load(ptr) => {
                let name = fresh_c(&mut self.counter, "l");
                let ct = ctype_of(&inst.ty);
                if ct == "void" {
                    self.set(v, "".into(), "void".into());
                } else if ct.ends_with(']') {
                    // Array load — C doesn't support array assignment, use memcpy
                    let pn = self.name(*ptr).to_owned();
                    let (decl_pre, decl_suf) = c_decl_parts(&inst.ty);
                    let decl_ct = format!("{}{}", decl_pre, decl_suf);
                    self.set(v, name.clone(), decl_ct);
                    writeln!(out, "  {} {}{};", decl_pre, name, decl_suf).unwrap();
                    writeln!(out, "  memcpy({}, {}, sizeof({}));", name, pn, name).unwrap();
                } else {
                    let pn = self.name(*ptr);
                    // ponytail: cancel *& when ptr is an inlined &-expression
                    let rhs = if self.is_indirect(*ptr) {
                        if let Some(inner) = strip_addr_of(pn) {
                            inner.to_owned()
                        } else {
                            format!("*{}", pn)
                        }
                    } else {
                        pn.to_owned()
                    };
                    self.set(v, name.clone(), ct.clone());
                    writeln!(out, "  {} {} = {};", ct, name, rhs).unwrap();
                }
            }

            InstKind::BinOp(op, lhs, rhs) => {
                let ct = ctype_of(&inst.ty);
                if ct == "void" {
                    self.set(v, "".into(), "void".into());
                } else {
                    let lhs_name = self.name(*lhs).to_owned();
                    let rhs_name = self.name(*rhs).to_owned();
                    let expr = format!("({} {} {})", lhs_name, binop_c(*op), rhs_name);
                    if self.use_counts.get(&v.0).copied().unwrap_or(0) <= 1 {
                        self.set_inline(v, expr, ct);
                    } else {
                        let name = fresh_c(&mut self.counter, "b");
                        self.set(v, name.clone(), ct.clone());
                        writeln!(out, "  {} {} = {};", ct, name, expr).unwrap();
                    }
                }
            }

            InstKind::UnOp(op, operand) => {
                let ct = ctype_of(&inst.ty);
                let mut operand_name = self.name(*operand).to_owned();
                let operand_ct = self
                    .ctypes
                    .get(operand.0 as usize)
                    .cloned()
                    .unwrap_or_default();
                if matches!(op, UnOp::Ref | UnOp::MutRef)
                    && self.inline_of.contains_key(&operand.0)
                    && !is_fat_repr(&inst.ty)
                {
                    let temporary = fresh_c(&mut self.counter, "ref_tmp");
                    writeln!(out, "  {} {} = {};", operand_ct, temporary, operand_name).unwrap();
                    operand_name = temporary;
                }
                // Ref is a no-op when the operand/value is already a pointer-like thing:
                // thin pointer: is_indirect (ctype ends with '*')
                // fat pointer: result type is a fat Ref (unsized inner, value already ptr+len)
                let is_noop_ref = matches!(op, UnOp::Ref | UnOp::MutRef)
                    && (self.is_indirect(*operand) || is_fat_repr(&inst.ty));
                let is_noop_deref =
                    matches!(op, UnOp::Deref) && operand_ct == "riddle_str" && ct == "riddle_str";
                let expr = if is_noop_ref || is_noop_deref {
                    operand_name
                } else {
                    let op_str = match op {
                        UnOp::Neg => "-",
                        UnOp::Not if matches!(inst.ty, Type::Int(_)) => "~",
                        UnOp::Not => "!",
                        UnOp::Ref => "&",
                        UnOp::MutRef => "&",
                        UnOp::Deref => "*",
                    };
                    format!("({}{})", op_str, operand_name)
                };
                if self.use_counts.get(&v.0).copied().unwrap_or(0) <= 1 {
                    self.set_inline(v, expr, ct);
                } else {
                    let name = fresh_c(&mut self.counter, "u");
                    self.set(v, name.clone(), ct.clone());
                    writeln!(out, "  {} {} = {};", ct, name, expr).unwrap();
                }
            }

            InstKind::Cmp(op, lhs, rhs) => {
                let lhs_name = self.name(*lhs).to_owned();
                let rhs_name = self.name(*rhs).to_owned();
                let lhs_type = self
                    .ctypes
                    .get(lhs.0 as usize)
                    .map(String::as_str)
                    .unwrap_or("");
                let expr = if lhs_type == "riddle_str" && matches!(op, CmpOp::Eq | CmpOp::Neq) {
                    let equal = format!(
                        "(({}).len == ({}).len && memcmp(({}).ptr, ({}).ptr, ({}).len) == 0)",
                        lhs_name, rhs_name, lhs_name, rhs_name, lhs_name
                    );
                    if matches!(op, CmpOp::Neq) {
                        format!("(!{})", equal)
                    } else {
                        equal
                    }
                } else {
                    format!("({} {} {})", lhs_name, cmpop_c(*op), rhs_name)
                };
                if self.use_counts.get(&v.0).copied().unwrap_or(0) <= 1 {
                    self.set_inline(v, expr, "bool".into());
                } else {
                    let name = fresh_c(&mut self.counter, "cmp");
                    self.set(v, name.clone(), "bool".into());
                    writeln!(out, "  bool {} = {};", name, expr).unwrap();
                }
            }

            InstKind::Cast(_op, value, target_ty) => {
                let ct = ctype_of(target_ty);
                let src = self.name(*value).to_owned();
                let expr = format!("(({}){})", ct, src);
                if self.use_counts.get(&v.0).copied().unwrap_or(0) <= 1 {
                    self.set_inline(v, expr, ct);
                } else {
                    let name = fresh_c(&mut self.counter, "cast");
                    self.set(v, name.clone(), ct.clone());
                    writeln!(out, "  {} {} = {};", ct, name, expr).unwrap();
                }
            }

            InstKind::StructValue(fields) => {
                let name = fresh_c(&mut self.counter, "s");
                let ct = ctype_of(&inst.ty);
                self.set(v, name.clone(), ct.clone());

                if let Type::Struct(st) = &inst.ty {
                    if st
                        .fields
                        .iter()
                        .any(|(_, field_ty)| matches!(field_ty, Type::Array(_, _)))
                    {
                        writeln!(out, "  {} {} = {{0}};", ct, name).unwrap();
                        for (index, value) in fields.iter().enumerate() {
                            let Some((field_name, field_ty)) = st.fields.get(index) else {
                                continue;
                            };
                            let field = sanitize(field_name);
                            let value_name = self.name(*value).to_owned();
                            if matches!(field_ty, Type::Array(_, _)) {
                                writeln!(
                                    out,
                                    "  memcpy({}.{}, {}, sizeof({}.{}));",
                                    name, field, value_name, name, field
                                )
                                .unwrap();
                            } else {
                                writeln!(out, "  {}.{} = {};", name, field, value_name).unwrap();
                            }
                        }
                    } else {
                        let flds: Vec<String> =
                            fields.iter().map(|f| self.name(*f).to_owned()).collect();
                        writeln!(out, "  {} {} = {{ {} }};", ct, name, flds.join(", ")).unwrap();
                    }
                } else {
                    let flds: Vec<String> =
                        fields.iter().map(|f| self.name(*f).to_owned()).collect();
                    writeln!(out, "  {} {} = {{ {} }};", ct, name, flds.join(", ")).unwrap();
                }
            }

            InstKind::SparseStructValue(fields) => {
                let name = fresh_c(&mut self.counter, "s");
                let ct = ctype_of(&inst.ty);
                self.set(v, name.clone(), ct.clone());
                writeln!(out, "  {} {} = {{0}};", ct, name).unwrap();

                let Type::Struct(st) = &inst.ty else {
                    return Err("sparse aggregate initializer requires a struct type".into());
                };
                for (index, value) in fields {
                    let Some((field_name, field_ty)) = st.fields.get(*index) else {
                        return Err(format!("aggregate field index {} is out of bounds", index));
                    };
                    let field = sanitize(field_name);
                    let value_name = self.name(*value).to_owned();
                    if matches!(field_ty, Type::Array(_, _)) {
                        writeln!(
                            out,
                            "  memcpy({}.{}, {}, sizeof({}.{}));",
                            name, field, value_name, name, field
                        )
                        .unwrap();
                    } else {
                        writeln!(out, "  {}.{} = {};", name, field, value_name).unwrap();
                    }
                }
            }

            InstKind::ArrayValue(elements) => {
                let name = fresh_c(&mut self.counter, "arr");
                let (decl_pre, decl_suf) = c_decl_parts(&inst.ty);
                let ct = format!("{}{}", decl_pre, decl_suf);
                self.set(v, name.clone(), ct.clone());
                let nested = matches!(&inst.ty, Type::Array(inner, _) if matches!(inner.as_ref(), Type::Array(..)));
                if nested {
                    writeln!(out, "  {} {}{} = {{0}};", decl_pre, name, decl_suf).unwrap();
                    for (index, element) in elements.iter().enumerate() {
                        writeln!(
                            out,
                            "  memcpy({}[{}], {}, sizeof({}[{}]));",
                            name,
                            index,
                            self.name(*element),
                            name,
                            index
                        )
                        .unwrap();
                    }
                } else {
                    let values = elements
                        .iter()
                        .map(|element| self.name(*element).to_owned())
                        .collect::<Vec<_>>();
                    writeln!(
                        out,
                        "  {} {}{} = {{ {} }};",
                        decl_pre,
                        name,
                        decl_suf,
                        values.join(", ")
                    )
                    .unwrap();
                }
            }

            InstKind::TupleValue(elements) => {
                let name = fresh_c(&mut self.counter, "tup");
                let ct = ctype_of(&inst.ty);
                self.set(v, name.clone(), ct.clone());
                let els: Vec<String> = elements.iter().map(|e| self.name(*e).to_owned()).collect();
                writeln!(out, "  {} {} = {{ {} }};", ct, name, els.join(", ")).unwrap();
            }

            InstKind::ExtractValue(aggregate, index) => {
                let ct = ctype_of(&inst.ty);
                let base = self.name(*aggregate).to_owned();
                let field = self
                    .struct_types
                    .get(&aggregate.0)
                    .and_then(|st| st.fields.get(*index))
                    .map(|(fname, _)| sanitize(fname))
                    .unwrap_or_else(|| format!("f{}", index));
                let expr = field_expr(&base, &field, self.is_indirect(*aggregate));
                if self.use_counts.get(&v.0).copied().unwrap_or(0) <= 1 {
                    self.set_inline(v, expr, ct);
                } else {
                    let name = fresh_c(&mut self.counter, "ev");
                    self.set(v, name.clone(), ct.clone());
                    writeln!(out, "  {} {} = {};", ct, name, expr).unwrap();
                }
            }

            InstKind::FieldPtr(base, index) => {
                let ct = ctype_of(&inst.ty);
                let base_name = self.name(*base).to_owned();
                let (field, field_ty) = self
                    .struct_types
                    .get(&base.0)
                    .and_then(|st| st.fields.get(*index))
                    .map(|(fname, ty)| (sanitize(fname), Some(ty)))
                    .unwrap_or_else(|| (format!("f{}", index), None));
                let mut field = field_expr(&base_name, &field, self.is_indirect(*base));
                let mut ty = field_ty;
                while let Some(Type::Array(inner, _)) = ty {
                    field.push_str("[0]");
                    ty = Some(inner);
                }
                let expr = format!("(&{})", field);
                if self.use_counts.get(&v.0).copied().unwrap_or(0) <= 1 {
                    self.set_inline(v, expr, ct);
                } else {
                    let name = fresh_c(&mut self.counter, "fp");
                    self.set(v, name.clone(), ct.clone());
                    writeln!(out, "  {} {} = {};", ct, name, expr).unwrap();
                }
            }

            InstKind::IndexPtr(base, index) => {
                let ct = ctype_of(&inst.ty);
                let base_name = self.name(*base).to_owned();
                let index_name = self.name(*index).to_owned();
                let element = match &inst.ty {
                    Type::Ptr(element) | Type::Ref(element, _) => element.as_ref(),
                    _ => &Type::Unit,
                };
                let expr = if !self.is_indirect(*base) && matches!(element, Type::Array(..)) {
                    format!("({}[{}])", base_name, index_name)
                } else {
                    let stride = array_leaf_count(element);
                    let index = if stride == 1 {
                        index_name
                    } else {
                        format!("(({}) * {})", index_name, stride)
                    };
                    format!("(&{}[{}])", base_name, index)
                };
                if self.use_counts.get(&v.0).copied().unwrap_or(0) <= 1 {
                    self.set_inline(v, expr, ct);
                } else {
                    let name = fresh_c(&mut self.counter, "ip");
                    self.set(v, name.clone(), ct.clone());
                    writeln!(out, "  {} {} = {};", ct, name, expr).unwrap();
                }
            }

            InstKind::Phi(pairs) => {
                let ct = ctype_of(&inst.ty);
                if ct == "void" {
                    // ponytail: void phi carries no value — skip variable declaration
                    self.set(v, "".into(), "void".into());
                    let _ = pairs;
                } else {
                    let _ = pairs;
                }
            }

            InstKind::Call(callee, args) => {
                let ct = ctype_of(&inst.ty);
                let callee_name = match callee {
                    FuncRef::Local(n) => n.clone(),
                    FuncRef::Intrinsic(n) => n.clone(),
                    FuncRef::Extern(n) => n.clone(),
                };
                // For extern calls, extract .ptr from fat pointer arguments
                let is_extern = matches!(callee, FuncRef::Extern(_));
                let args_str: Vec<String> = args
                    .iter()
                    .map(|a| {
                        let arg_name = self.name(*a).to_owned();
                        let arg_ct = self
                            .ctypes
                            .get(a.0 as usize)
                            .map(|s| s.as_str())
                            .unwrap_or("");
                        if is_extern && arg_ct == "riddle_str" && !is_builtin_extern(&callee_name) {
                            if self.is_indirect(*a) {
                                format!("{}->ptr", arg_name)
                            } else {
                                format!("{}.ptr", arg_name)
                            }
                        } else {
                            arg_name
                        }
                    })
                    .collect();
                // void return — emit call as a statement, no assignment
                if matches!(&inst.ty, Type::Unit | Type::Never | Type::Void) {
                    writeln!(out, "  {}({});", callee_name, args_str.join(", ")).unwrap();
                    self.set(v, "".into(), "void".into());
                } else if is_extern && !is_builtin_extern(&callee_name) && is_fat_repr(&inst.ty) {
                    let ffi_name = fresh_c(&mut self.counter, "ffi_str");
                    let name = fresh_c(&mut self.counter, "call");
                    self.set(v, name.clone(), ct.clone());
                    writeln!(
                        out,
                        "  const char* {} = {}({});",
                        ffi_name,
                        callee_name,
                        args_str.join(", ")
                    )
                    .unwrap();
                    writeln!(
                        out,
                        "  {} {} = (riddle_str){{ {}, {} ? strlen({}) : 0 }};",
                        ct, name, ffi_name, ffi_name, ffi_name
                    )
                    .unwrap();
                } else {
                    let name = fresh_c(&mut self.counter, "call");
                    self.set(v, name.clone(), ct.clone());
                    writeln!(
                        out,
                        "  {} {} = {}({});",
                        ct,
                        name,
                        callee_name,
                        args_str.join(", ")
                    )
                    .unwrap();
                }
            }

            InstKind::FunctionRef(function) => {
                let name = match function {
                    FuncRef::Local(name) | FuncRef::Intrinsic(name) | FuncRef::Extern(name) => {
                        sanitize(name)
                    }
                };
                self.set_inline(v, name, ctype_of(&inst.ty));
            }

            InstKind::CallIndirect(callee, args) => {
                let ct = ctype_of(&inst.ty);
                let callee = self.name(*callee).to_owned();
                let args = args
                    .iter()
                    .map(|arg| self.name(*arg).to_owned())
                    .collect::<Vec<_>>()
                    .join(", ");
                if matches!(&inst.ty, Type::Unit | Type::Never | Type::Void) {
                    writeln!(out, "  {}({});", callee, args).unwrap();
                    self.set(v, "".into(), "void".into());
                } else {
                    let name = fresh_c(&mut self.counter, "call");
                    self.set(v, name.clone(), ct.clone());
                    writeln!(out, "  {} {} = {}({});", ct, name, callee, args).unwrap();
                }
            }
        }
        Ok(())
    }

    fn emit_phi_assignments(
        &self,
        func: &Function,
        target: crate::value::BlockId,
        from: crate::value::BlockId,
        out: &mut String,
        indent: &str,
    ) {
        let block = &func.blocks[target];
        for (index, inst) in block.insts.iter().enumerate() {
            let InstKind::Phi(pairs) = &inst.kind else {
                continue;
            };
            if ctype_of(&inst.ty) == "void" {
                continue;
            }
            let Some((incoming, _)) = pairs.iter().find(|(_, pred)| *pred == from) else {
                continue;
            };
            let phi_value = Value(block.start_value + index as u32);
            writeln!(
                out,
                "{}{} = {};",
                indent,
                self.name(phi_value),
                self.name(*incoming)
            )
            .unwrap();
        }
    }
}

/// Collect unique struct types from all instructions across the module.
fn collect_structs(module: &Module) -> Vec<StructType> {
    let mut seen: HashMap<String, StructType> = HashMap::new();
    for &fid in &module.function_order {
        let func = &module.functions[fid];
        collect_struct_type(&func.ret_type, &mut seen);
        for param in &func.params {
            collect_struct_type(&param.ty, &mut seen);
        }
        for (_bid, block) in func.blocks.iter() {
            for inst in &block.insts {
                collect_struct_type(&inst.ty, &mut seen);
            }
        }
    }
    for external in &module.externs {
        collect_struct_type(&external.ret_type, &mut seen);
        for param in &external.params {
            collect_struct_type(param, &mut seen);
        }
    }
    let mut out: Vec<StructType> = seen.into_values().collect();
    out.sort_by(|a, b| {
        struct_depth(a)
            .cmp(&struct_depth(b))
            .then_with(|| a.name.cmp(&b.name))
    });
    out
}

fn collect_fn_ptrs(module: &Module) -> Vec<FnPtrType> {
    let mut seen = HashSet::new();
    for &fid in &module.function_order {
        let function = &module.functions[fid];
        collect_fn_ptr_type(&function.ret_type, &mut seen);
        for param in &function.params {
            collect_fn_ptr_type(&param.ty, &mut seen);
        }
        for (_, block) in function.blocks.iter() {
            for inst in &block.insts {
                collect_fn_ptr_type(&inst.ty, &mut seen);
            }
        }
    }
    for external in &module.externs {
        collect_fn_ptr_type(&external.ret_type, &mut seen);
        for param in &external.params {
            collect_fn_ptr_type(param, &mut seen);
        }
    }
    let mut signatures = seen.into_iter().collect::<Vec<_>>();
    signatures.sort_by_key(fn_ptr_name);
    signatures
}

fn collect_fn_ptr_type(ty: &Type, seen: &mut HashSet<FnPtrType>) {
    match ty {
        Type::FnPtr(signature) => {
            if seen.insert(signature.clone()) {
                for param in &signature.params {
                    collect_fn_ptr_type(param, seen);
                }
                collect_fn_ptr_type(&signature.ret, seen);
            }
        }
        Type::Struct(strukt) => {
            for (_, field) in &strukt.fields {
                collect_fn_ptr_type(field, seen);
            }
        }
        Type::Ptr(inner) | Type::Ref(inner, _) | Type::Array(inner, _) => {
            collect_fn_ptr_type(inner, seen)
        }
        Type::Tuple(elements) => {
            for element in elements {
                collect_fn_ptr_type(element, seen);
            }
        }
        _ => {}
    }
}

fn module_has_heap_alloc(module: &Module) -> bool {
    module.function_order.iter().any(|fid| {
        module.functions[*fid].blocks.iter().any(|(_, block)| {
            block
                .insts
                .iter()
                .any(|inst| matches!(inst.kind, InstKind::HeapAlloc(_)))
        })
    })
}

fn collect_struct_type(ty: &Type, seen: &mut HashMap<String, StructType>) {
    match ty {
        Type::Struct(st) => {
            if seen.insert(st.name.clone(), st.clone()).is_some() {
                return;
            }
            for (_, field_ty) in &st.fields {
                collect_struct_type(field_ty, seen);
            }
        }
        Type::Ptr(inner) | Type::Ref(inner, _) | Type::Array(inner, _) => {
            collect_struct_type(inner, seen)
        }
        Type::Tuple(elems) => {
            for elem in elems {
                collect_struct_type(elem, seen);
            }
        }
        Type::FnPtr(signature) => {
            for param in &signature.params {
                collect_struct_type(param, seen);
            }
            collect_struct_type(&signature.ret, seen);
        }
        _ => {}
    }
}

fn struct_depth(st: &StructType) -> usize {
    1 + st
        .fields
        .iter()
        .map(|(_, ty)| type_struct_depth(ty))
        .max()
        .unwrap_or(0)
}

fn type_struct_depth(ty: &Type) -> usize {
    match ty {
        Type::Struct(st) => struct_depth(st),
        Type::Ptr(inner) | Type::Ref(inner, _) | Type::Array(inner, _) => type_struct_depth(inner),
        Type::Tuple(elems) => elems.iter().map(type_struct_depth).max().unwrap_or(0),
        _ => 0,
    }
}

fn has_extern(module: &Module, name: &str) -> bool {
    module.externs.iter().any(|ext| ext.name == name)
}

fn is_builtin_extern(name: &str) -> bool {
    matches!(
        name,
        "str_len" | "str_byte" | "str_from_raw" | "vector_grow"
    ) || name.starts_with("size_of_ptr__")
}

/// Count how many times each value is referenced as an operand.
fn count_uses(func: &Function) -> HashMap<u32, u32> {
    let mut uses: HashMap<u32, u32> = HashMap::new();
    for (_bid, block) in func.blocks.iter() {
        for inst in &block.insts {
            for v in inst_operands(inst) {
                *uses.entry(v.0).or_insert(0) += 1;
            }
        }
        match &block.terminator {
            Terminator::Return(Some(v)) => {
                *uses.entry(v.0).or_insert(0) += 1;
            }
            Terminator::CondBranch(cond, _, _) => {
                *uses.entry(cond.0).or_insert(0) += 1;
            }
            _ => {}
        }
    }
    uses
}

/// Collect all Value operands referenced by an instruction.
fn inst_operands(inst: &Inst) -> Vec<Value> {
    match &inst.kind {
        InstKind::Store(value, ptr) => vec![*value, *ptr],
        InstKind::Load(ptr) => vec![*ptr],
        InstKind::BinOp(_, lhs, rhs) => vec![*lhs, *rhs],
        InstKind::UnOp(_, operand) => vec![*operand],
        InstKind::Cmp(_, lhs, rhs) => vec![*lhs, *rhs],
        InstKind::Cast(_, value, _) => vec![*value],
        InstKind::StructValue(fields) => fields.clone(),
        InstKind::SparseStructValue(fields) => fields.iter().map(|(_, value)| *value).collect(),
        InstKind::ArrayValue(elements) => elements.clone(),
        InstKind::TupleValue(elements) => elements.clone(),
        InstKind::ExtractValue(aggregate, _) => vec![*aggregate],
        InstKind::FieldPtr(base, _) => vec![*base],
        InstKind::IndexPtr(base, index) => vec![*base, *index],
        InstKind::Phi(pairs) => pairs.iter().map(|(v, _)| *v).collect(),
        InstKind::Call(_, args) => args.clone(),
        InstKind::CallIndirect(callee, args) => {
            let mut values = vec![*callee];
            values.extend(args);
            values
        }
        _ => vec![], // Const, HeapAlloc, Alloca: no operands
    }
}

fn fresh_c(ctr: &mut u64, prefix: &str) -> String {
    *ctr += 1;
    format!("{}{}", prefix, ctr)
}

fn c_return_type(func: &Function) -> String {
    if func.name == "main" && matches!(func.ret_type, Type::Unit) {
        "int".into()
    } else {
        ctype_of(&func.ret_type)
    }
}

fn ctype_of(ty: &Type) -> String {
    match ty {
        Type::Int(ity) => match ity {
            IntTy::I8 | IntTy::U8 => "int8_t".into(),
            IntTy::I16 | IntTy::U16 => "int16_t".into(),
            IntTy::I32 | IntTy::U32 => "int32_t".into(),
            IntTy::I64 | IntTy::U64 | IntTy::Isize | IntTy::Usize => "int64_t".into(),
            IntTy::I128 | IntTy::U128 => "__int128".into(),
        },
        Type::Float(fty) => match fty {
            // ponytail: F16 uses C23 _Float16; fall back to float on older compilers
            FloatTy::F16 => "_Float16".into(),
            FloatTy::F32 => "float".into(),
            FloatTy::F64 => "double".into(),
            FloatTy::F128 => "riddle_f128".into(),
        },
        Type::Bool => "bool".into(),
        Type::Char => "char".into(),
        Type::Str => "riddle_str".into(),
        Type::Ptr(inner) => pointer_ctype(inner),
        Type::Ref(inner, _) => {
            if !inner.is_sized() {
                "riddle_str".into()
            } else {
                pointer_ctype(inner)
            }
        }
        Type::Struct(s) => s.name.clone(),
        Type::Array(..) => {
            let (prefix, suffix) = c_decl_parts(ty);
            format!("{}{}", prefix, suffix)
        }
        Type::Tuple(elems) => {
            let fields: Vec<String> = elems
                .iter()
                .enumerate()
                .map(|(i, t)| format!("{} f{};", ctype_of(t), i))
                .collect();
            format!("struct {{ {} }}", fields.join(" "))
        }
        Type::Enum(e) => format!("enum_{}", e.name),
        Type::FnPtr(signature) => fn_ptr_name(signature),
        Type::Unit | Type::Never | Type::Void => "void".into(),
    }
}

fn pointer_ctype(inner: &Type) -> String {
    let mut pointee = inner;
    while let Type::Array(element, _) = pointee {
        pointee = element;
    }
    format!("{}*", ctype_of(pointee))
}

fn array_leaf_count(ty: &Type) -> usize {
    match ty {
        Type::Array(inner, len) => len.saturating_mul(array_leaf_count(inner)),
        _ => 1,
    }
}

fn fn_ptr_name(signature: &FnPtrType) -> String {
    let mut hasher = DefaultHasher::new();
    signature.hash(&mut hasher);
    format!("riddle_fn_{:016x}", hasher.finish())
}

/// C type for FFI declarations — `&str` maps to plain `const char*` because C
/// functions expect C strings, not the fat pointer struct.
fn ctype_of_ffi(ty: &Type) -> String {
    match ty {
        Type::Ref(inner, _) if !inner.is_sized() => "const char*".into(),
        _ => ctype_of(ty),
    }
}

/// Whether this type is represented as a fat pointer (struct) in C.
fn is_fat_repr(ty: &Type) -> bool {
    match ty {
        Type::Str => true,
        Type::Ref(inner, _) => !inner.is_sized(),
        _ => false,
    }
}

fn c_string_parts(value: &str) -> (String, usize) {
    if let Some(body) = raw_string_body(value) {
        return (escape_c_string(body), body.len());
    }

    let inner = if value.len() >= 2 {
        &value[1..value.len() - 1]
    } else {
        value
    };
    (inner.to_string(), inner.len())
}

fn raw_string_body(text: &str) -> Option<&str> {
    let rest = text.strip_prefix('r')?;
    let hashes = rest.bytes().take_while(|&b| b == b'#').count();
    let open_quote = 1 + hashes;
    if text.as_bytes().get(open_quote) != Some(&b'"') {
        return None;
    }

    let suffix_len = 1 + hashes;
    let suffix_start = text.len().checked_sub(suffix_len)?;
    if suffix_start <= open_quote || text.as_bytes().get(suffix_start) != Some(&b'"') {
        return None;
    }
    if !text.as_bytes()[suffix_start + 1..]
        .iter()
        .all(|&b| b == b'#')
    {
        return None;
    }

    Some(&text[open_quote + 1..suffix_start])
}

fn escape_c_string(text: &str) -> String {
    let mut out = String::new();
    for ch in text.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\0' => out.push_str("\\0"),
            _ => out.push(ch),
        }
    }
    out
}

fn struct_type_for_field_base(ty: &Type) -> Option<&StructType> {
    match ty {
        Type::Struct(st) => Some(st),
        Type::Ptr(inner) | Type::Ref(inner, _) => match inner.as_ref() {
            Type::Struct(st) => Some(st),
            _ => None,
        },
        _ => None,
    }
}

fn field_expr(base: &str, field: &str, indirect: bool) -> String {
    if indirect {
        format!("{}->{}", base, field)
    } else {
        format!("{}.{}", base, field)
    }
}

fn pointee_ct(ty: &Type) -> String {
    match ty {
        Type::Ptr(inner) | Type::Ref(inner, _) => ctype_of(inner),
        _ => "void".into(),
    }
}

/// Split a MIR type into C declaration parts: (prefix, suffix_after_var_name).
/// e.g. Array(Array(Foo, 3), 4) → ("Foo", "[4][3]")
fn c_decl_parts(ty: &Type) -> (String, String) {
    match ty {
        Type::Array(inner, len) => {
            let (pre, suf) = c_decl_parts(inner);
            (pre, format!("[{}]{}", len, suf))
        }
        _ => (ctype_of(ty), String::new()),
    }
}

fn c_param_decl(ty: &Type, name: &str) -> String {
    let (pre, suf) = c_decl_parts(ty);
    format!("{} {}{}", pre, name, suf)
}

fn binop_c(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
        BinOp::BitAnd => "&",
        BinOp::BitOr => "|",
        BinOp::BitXor => "^",
        BinOp::Shl => "<<",
        BinOp::Shr => ">>",
    }
}

fn cmpop_c(op: CmpOp) -> &'static str {
    match op {
        CmpOp::Eq => "==",
        CmpOp::Neq => "!=",
        CmpOp::Lt => "<",
        CmpOp::Gt => ">",
        CmpOp::LtEq => "<=",
        CmpOp::GtEq => ">=",
    }
}

/// If expr is `(&inner)`, return `inner`. Ponytail: cancel *& from inlined FieldPtr/IndexPtr.
fn strip_addr_of(expr: &str) -> Option<&str> {
    if expr.starts_with("(&") && expr.ends_with(')') {
        Some(&expr[2..expr.len() - 1])
    } else {
        None
    }
}

fn sanitize(name: &str) -> String {
    name.replace(['-', ':', '<', '>'], "_")
}
