use std::fmt::Write;

use crate::backend::Backend;
use crate::func::Function;
use crate::instr::*;
use crate::module::Module;
use crate::value::{FuncRef, Value};

#[derive(Debug, Default)]
pub struct JsBackend {
    /// Variable names indexed by MIR Value number.
    names: Vec<String>,
    /// Which MIR Values are heap-allocated (GC boxes).
    heap: Vec<bool>,
    /// Fresh name counter.
    counter: u64,
}

impl JsBackend {
    pub fn new() -> Self {
        Self::default()
    }

    fn ensure(&mut self, v: Value) {
        let idx = v.0 as usize;
        if idx >= self.names.len() {
            self.names.resize(idx + 1, String::new());
            self.heap.resize(idx + 1, false);
        }
    }

    fn set_name(&mut self, v: Value, name: String) {
        self.ensure(v);
        self.names[v.0 as usize] = name;
    }

    fn name(&self, v: Value) -> &str {
        self.names
            .get(v.0 as usize)
            .map(|s| s.as_str())
            .unwrap_or("?")
    }

    fn set_heap(&mut self, v: Value) {
        self.ensure(v);
        self.heap[v.0 as usize] = true;
    }

    fn is_heap(&self, v: Value) -> bool {
        self.heap.get(v.0 as usize).copied().unwrap_or(false)
    }
}

impl Backend for JsBackend {
    type Error = std::fmt::Error;

    fn compile(&mut self, module: &Module) -> Result<String, Self::Error> {
        let mut out = String::new();
        writeln!(out, "// Generated by Riddle MIR → JS backend")?;
        writeln!(out)?;

        for &fid in &module.function_order {
            let func = &module.functions[fid];
            self.compile_function(func, &mut out)?;
            writeln!(out)?;
        }

        Ok(out)
    }

    fn name(&self) -> &'static str {
        "js"
    }
}

impl JsBackend {
    fn compile_function(
        &mut self,
        func: &Function,
        out: &mut String,
    ) -> Result<(), std::fmt::Error> {
        self.names.clear();
        self.heap.clear();

        // 参数绑定
        for p in &func.params {
            let name = sanitize(&p.name);
            self.set_name(p.value, name);
        }

        let param_strs: Vec<String> = func.params.iter().map(|p| sanitize(&p.name)).collect();

        write!(out, "function {}(", func.name)?;
        for (i, p) in param_strs.iter().enumerate() {
            if i > 0 {
                write!(out, ", ")?;
            }
            write!(out, "{}", p)?;
        }
        writeln!(out, ") {{")?;

        for (_bid, block) in func.blocks.iter() {
            if let Some(ref label) = block.label {
                writeln!(out, "  // block: {}", label)?;
            }

            for (i, inst) in block.insts.iter().enumerate() {
                let v = Value(block.start_value + i as u32);
                self.emit_inst(inst, v, out)?;
            }

            match &block.terminator {
                Terminator::Return(val) => match val {
                    Some(v) => {
                        let n = self.name(*v);
                        if self.is_heap(*v) {
                            writeln!(out, "  return {}.{};", n, "_box")?;
                        } else {
                            writeln!(out, "  return {};", n)?;
                        }
                    }
                    None => writeln!(out, "  return;")?,
                },
                Terminator::Branch(_) | Terminator::CondBranch(_, _, _) => {}
            }
        }

        writeln!(out, "}}")?;
        Ok(())
    }

    fn emit_inst(
        &mut self,
        inst: &Inst,
        v: Value,
        out: &mut String,
    ) -> Result<(), std::fmt::Error> {
        match &inst.kind {
            InstKind::Const(c) => {
                let name = self.fresh("c");
                self.set_name(v, name.clone());
                writeln!(out, "  let {} = {};", name, const_js(c))?;
            }
            InstKind::HeapAlloc(_ty) => {
                let name = self.fresh("h");
                self.set_name(v, name.clone());
                self.set_heap(v);
                // 分配 GC 可追踪的 box 对象
                writeln!(out, "  let {} = {{ {}: null }};", name, "_box")?;
            }
            InstKind::Alloca(_ty) => {
                let name = self.fresh("a");
                self.set_name(v, name.clone());
                writeln!(out, "  let {} = null;", name)?;
            }
            InstKind::Store(value, ptr) => {
                let vn = self.name(*value);
                let pn = self.name(*ptr);
                if self.is_heap(*ptr) {
                    writeln!(out, "  {}.{} = {};", pn, "_box", vn)?;
                } else {
                    writeln!(out, "  {} = {};", pn, vn)?;
                }
            }
            InstKind::Load(ptr) => {
                let name = self.fresh("l");
                self.set_name(v, name.clone());
                let pn = self.name(*ptr);
                if self.is_heap(*ptr) {
                    writeln!(out, "  let {} = {}.{};", name, pn, "_box")?;
                } else {
                    writeln!(out, "  let {} = {};", name, pn)?;
                }
            }
            InstKind::BinOp(op, lhs, rhs) => {
                let name = self.fresh("b");
                self.set_name(v, name.clone());
                writeln!(
                    out,
                    "  let {} = {} {} {};",
                    name,
                    self.name(*lhs),
                    binop_js(*op),
                    self.name(*rhs)
                )?;
            }
            InstKind::UnOp(op, operand) => {
                let name = self.fresh("u");
                self.set_name(v, name.clone());
                match op {
                    UnOp::Neg => writeln!(out, "  let {} = -{};", name, self.name(*operand))?,
                    UnOp::Not => writeln!(out, "  let {} = !{};", name, self.name(*operand))?,
                    _ => writeln!(out, "  let {} = {};", name, self.name(*operand))?,
                }
            }
            InstKind::Cmp(op, lhs, rhs) => {
                let name = self.fresh("cmp");
                self.set_name(v, name.clone());
                writeln!(
                    out,
                    "  let {} = {} {} {};",
                    name,
                    self.name(*lhs),
                    cmpop_js(*op),
                    self.name(*rhs)
                )?;
            }
            InstKind::Call(callee, args) => {
                let name = self.fresh("call");
                self.set_name(v, name.clone());
                let args_str: Vec<String> = args.iter().map(|a| self.name(*a).to_owned()).collect();
                let callee_str = callee_js(callee);
                writeln!(
                    out,
                    "  let {} = {}({});",
                    name,
                    callee_str,
                    args_str.join(", ")
                )?;
            }
            InstKind::StructValue(fields) => {
                let name = self.fresh("s");
                self.set_name(v, name.clone());
                let flds: Vec<String> = fields.iter().map(|a| self.name(*a).to_owned()).collect();
                writeln!(out, "  let {} = {{{}}};", name, flds.join(", "))?;
            }
            InstKind::ArrayValue(elems) => {
                let name = self.fresh("arr");
                self.set_name(v, name.clone());
                let el: Vec<String> = elems.iter().map(|a| self.name(*a).to_owned()).collect();
                writeln!(out, "  let {} = [{}];", name, el.join(", "))?;
            }
            _ => {
                let name = self.fresh("x");
                self.set_name(v, name.clone());
                writeln!(out, "  let {} = null;", name)?;
            }
        }
        Ok(())
    }

    fn fresh(&mut self, prefix: &str) -> String {
        self.counter += 1;
        format!("{}{}", prefix, self.counter)
    }
}

fn const_js(c: &ConstValue) -> String {
    match c {
        ConstValue::Int(v, _) => v.to_string(),
        ConstValue::Float(v, _) => {
            if v.is_nan() {
                "NaN".into()
            } else if v.is_infinite() && v.is_sign_positive() {
                "Infinity".into()
            } else if v.is_infinite() {
                "-Infinity".into()
            } else {
                v.to_string()
            }
        }
        ConstValue::Bool(v) => v.to_string(),
        ConstValue::String(v) => format!("{:?}", v),
        ConstValue::Char(v) => format!("{:?}", v),
        ConstValue::Unit => "null".into(),
    }
}

fn binop_js(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
        BinOp::BitAnd => "&",
        BinOp::BitOr => "|",
        BinOp::BitXor => "^",
        BinOp::Shl => "<<",
        BinOp::Shr => ">>",
    }
}

fn cmpop_js(op: CmpOp) -> &'static str {
    match op {
        CmpOp::Eq => "===",
        CmpOp::Neq => "!==",
        CmpOp::Lt => "<",
        CmpOp::Gt => ">",
        CmpOp::LtEq => "<=",
        CmpOp::GtEq => ">=",
    }
}

fn callee_js(callee: &FuncRef) -> String {
    match callee {
        FuncRef::Local(name) => sanitize(name),
        FuncRef::Intrinsic(name) => match name.as_str() {
            "print" => "console.log".into(),
            _ => sanitize(name),
        },
    }
}

fn sanitize(name: &str) -> String {
    name.replace('-', "_")
        .replace(':', "_")
        .replace('<', "_")
        .replace('>', "_")
}
