use std::fmt::Write;

use crate::backend::Backend;
use crate::func::Function;
use crate::instr::*;
use crate::module::Module;
use crate::value::{FuncRef, Value};

#[derive(Debug, Default)]
pub struct LuaBackend {
    /// Variable names indexed by MIR Value number.
    names: Vec<String>,
    /// Which MIR Values are heap-allocated (GC boxes).
    heap: Vec<bool>,
    /// Fresh name counter.
    counter: u64,
}

impl LuaBackend {
    pub fn new() -> Self {
        Self::default()
    }

    fn ensure(&mut self, v: Value) {
        let idx = v.0 as usize;
        if idx >= self.names.len() {
            self.names.resize(idx + 1, String::new());
            self.heap.resize(idx + 1, false);
        }
    }

    fn set_name(&mut self, v: Value, name: String) {
        self.ensure(v);
        self.names[v.0 as usize] = name;
    }

    fn name(&self, v: Value) -> &str {
        self.names
            .get(v.0 as usize)
            .map(|s| s.as_str())
            .unwrap_or("nil")
    }

    fn set_heap(&mut self, v: Value) {
        self.ensure(v);
        self.heap[v.0 as usize] = true;
    }

    fn is_heap(&self, v: Value) -> bool {
        self.heap.get(v.0 as usize).copied().unwrap_or(false)
    }
}

impl Backend for LuaBackend {
    type Error = std::fmt::Error;

    fn compile(&mut self, module: &Module) -> Result<String, Self::Error> {
        let mut out = String::new();
        writeln!(out, "-- Generated by Riddle MIR → Lua backend")?;
        writeln!(out)?;

        for &fid in &module.function_order {
            let func = &module.functions[fid];
            self.compile_function(func, &mut out)?;
            writeln!(out)?;
        }

        Ok(out)
    }

    fn name(&self) -> &'static str {
        "lua"
    }
}

impl LuaBackend {
    fn compile_function(
        &mut self,
        func: &Function,
        out: &mut String,
    ) -> Result<(), std::fmt::Error> {
        self.names.clear();
        self.heap.clear();
        self.counter = 0;

        // 参数绑定
        for p in &func.params {
            let name = sanitize(&p.name);
            self.set_name(p.value, name);
        }

        let param_strs: Vec<String> = func.params.iter().map(|p| sanitize(&p.name)).collect();

        write!(out, "function {}(", func.name)?;
        for (i, p) in param_strs.iter().enumerate() {
            if i > 0 {
                write!(out, ", ")?;
            }
            write!(out, "{}", p)?;
        }
        writeln!(out, ")")?;

        for (_bid, block) in func.blocks.iter() {
            if let Some(ref label) = block.label {
                writeln!(out, "  -- block: {}", label)?;
            }

            for (i, inst) in block.insts.iter().enumerate() {
                let v = Value(block.start_value + i as u32);
                self.emit_inst(inst, v, out)?;
            }

            match &block.terminator {
                Terminator::Return(val) => match val {
                    Some(v) => {
                        let n = self.name(*v);
                        if self.is_heap(*v) {
                            writeln!(out, "  return {}.{}", n, "_box")?;
                        } else {
                            writeln!(out, "  return {}", n)?;
                        }
                    }
                    None => writeln!(out, "  return")?,
                },
                Terminator::Branch(_) | Terminator::CondBranch(_, _, _) => {}
            }
        }

        writeln!(out, "end")?;
        Ok(())
    }

    fn emit_inst(
        &mut self,
        inst: &Inst,
        v: Value,
        out: &mut String,
    ) -> Result<(), std::fmt::Error> {
        match &inst.kind {
            InstKind::Const(c) => {
                let name = self.fresh("c");
                self.set_name(v, name.clone());
                writeln!(out, "  local {} = {}", name, const_lua(c))?;
            }
            InstKind::HeapAlloc(_ty) => {
                let name = self.fresh("h");
                self.set_name(v, name.clone());
                self.set_heap(v);
                writeln!(out, "  local {} = {{ {} = nil }}", name, "_box")?;
            }
            InstKind::Alloca(_ty) => {
                let name = self.fresh("a");
                self.set_name(v, name.clone());
                writeln!(out, "  local {} = nil", name)?;
            }
            InstKind::Store(value, ptr) => {
                let vn = self.name(*value);
                let pn = self.name(*ptr);
                if self.is_heap(*ptr) {
                    writeln!(out, "  {}.{} = {}", pn, "_box", vn)?;
                } else {
                    writeln!(out, "  {} = {}", pn, vn)?;
                }
            }
            InstKind::Load(ptr) => {
                let name = self.fresh("l");
                self.set_name(v, name.clone());
                let pn = self.name(*ptr);
                if self.is_heap(*ptr) {
                    writeln!(out, "  local {} = {}.{}", name, pn, "_box")?;
                } else {
                    writeln!(out, "  local {} = {}", name, pn)?;
                }
            }
            InstKind::BinOp(op, lhs, rhs) => {
                let name = self.fresh("b");
                self.set_name(v, name.clone());
                writeln!(
                    out,
                    "  local {} = {} {} {}",
                    name,
                    self.name(*lhs),
                    binop_lua(*op),
                    self.name(*rhs)
                )?;
            }
            InstKind::UnOp(op, operand) => {
                let name = self.fresh("u");
                self.set_name(v, name.clone());
                let o = self.name(*operand);
                match op {
                    UnOp::Neg => writeln!(out, "  local {} = -{}", name, o)?,
                    UnOp::Not => writeln!(out, "  local {} = not {}", name, o)?,
                    _ => writeln!(out, "  local {} = {}", name, o)?,
                }
            }
            InstKind::Cmp(op, lhs, rhs) => {
                let name = self.fresh("cmp");
                self.set_name(v, name.clone());
                writeln!(
                    out,
                    "  local {} = {} {} {}",
                    name,
                    self.name(*lhs),
                    cmpop_lua(*op),
                    self.name(*rhs)
                )?;
            }
            InstKind::Call(callee, args) => {
                let name = self.fresh("call");
                self.set_name(v, name.clone());
                let args_str: Vec<String> = args.iter().map(|a| self.name(*a).to_owned()).collect();
                let callee_str = callee_lua(callee);
                writeln!(
                    out,
                    "  local {} = {}({})",
                    name,
                    callee_str,
                    args_str.join(", ")
                )?;
            }
            InstKind::StructValue(fields) | InstKind::ArrayValue(fields) => {
                let name = self.fresh("s");
                self.set_name(v, name.clone());
                let flds: Vec<String> = fields.iter().map(|a| self.name(*a).to_owned()).collect();
                writeln!(out, "  local {} = {{{}}}", name, flds.join(", "))?;
            }
            _ => {
                let name = self.fresh("x");
                self.set_name(v, name.clone());
                writeln!(out, "  local {} = nil", name)?;
            }
        }
        Ok(())
    }

    fn fresh(&mut self, prefix: &str) -> String {
        self.counter += 1;
        format!("{}{}", prefix, self.counter)
    }
}

fn const_lua(c: &ConstValue) -> String {
    match c {
        ConstValue::Int(v, _) => v.to_string(),
        ConstValue::Float(v, _) => {
            if v.is_nan() {
                "(0/0)".into()
            } else if v.is_infinite() && v.is_sign_positive() {
                "math.huge".into()
            } else if v.is_infinite() {
                "-math.huge".into()
            } else {
                v.to_string()
            }
        }
        ConstValue::Bool(v) => {
            if *v {
                "true".into()
            } else {
                "false".into()
            }
        }
        ConstValue::String(v) => format!("{:?}", v),
        ConstValue::Char(v) => format!("{:?}", v),
        ConstValue::Unit => "nil".into(),
    }
}

fn binop_lua(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
        BinOp::BitAnd => "&",
        BinOp::BitOr => "|",
        BinOp::BitXor => "~",
        BinOp::Shl => "<<",
        BinOp::Shr => ">>",
    }
}

fn cmpop_lua(op: CmpOp) -> &'static str {
    match op {
        CmpOp::Eq => "==",
        CmpOp::Neq => "~=",
        CmpOp::Lt => "<",
        CmpOp::Gt => ">",
        CmpOp::LtEq => "<=",
        CmpOp::GtEq => ">=",
    }
}

fn callee_lua(callee: &FuncRef) -> String {
    match callee {
        FuncRef::Local(name) => sanitize(name),
        FuncRef::Intrinsic(name) => sanitize(name),
    }
}

fn sanitize(name: &str) -> String {
    name.replace('-', "_")
        .replace(':', "_")
        .replace('<', "_")
        .replace('>', "_")
}
